export default function() {
  return {
    'Damage Calculation': {
      'build': '配置',
      'create build': '新增配置',
      'result': {
        'modes': {
          'expected: selected calc struct': '伤害期望值',
          'expected': '综合伤害期望值',
          'range': '伤害区间',
        },
        'caption': {
          'expected: selected calc struct': '考虑稳定度计算出来的伤害期望值。',
          'expected': '考虑爆击率及稳定度计算出来的伤害期望值。',
          'range': '根据稳定度计算出的伤害最大值及最小值。',
        },
      },
      'mode': {
        'critical': '暴击时伤害',
        'without_critical': '无暴击时伤害',
      },
      'compare': {
        'select build': '选择要比较的配置',
      },
      'tips': {
        'At least one build must be kept': '要至少保留一个配置0.0',
        'Successfully removed build': '移除配置「$0」成功。',
      },
      'item base: title': {
        'physical': '物理伤害',
        'magic': '魔法伤害',
        'atk': 'ATK',
        'matk': 'MATK',
        'sub_atk': '副手ATK',
        'sub_stability': '副手倍率',
        'skill_level_two_handed': '((!双手合持))等级',
        'character_level': '角色等级',
        'target_level': '目标等级',
        'target_def': '目标DEF',
        'target_mdef': '目标MDEF',
        'physical_pierce': '物理贯穿',
        'magic_pierce': '魔法贯穿',
        'skill_constant': '技能常数',
        'unsheathe_attack_constant': '拔刀攻击',
        'other_constant': '其它常数',
        'skill_multiplier': '技能倍率',
        'critical_damage': '暴击伤害',
        'critical_rate': '暴击率',
        'target_critical_rate_resistance': '目标暴击率抗性',
        'magic_critical_rate_conversion_rate': '法术暴击率转化率',
        'magic_critical_damage_conversion_rate': '法术暴击伤害转化率',
        'short_range_damage': '近距离威力',
        'long_range_damage': '远距离威力',
        'unsheathe_attack_multiplier': '拔刀攻击%',
        'stronger_against_neutral': '对无属性',
        'stronger_against_fire': '对火属性',
        'stronger_against_water': '对水属性',
        'stronger_against_earth': '对地属性',
        'stronger_against_wind': '对风属性',
        'stronger_against_light': '对光属性',
        'stronger_against_dark': '对暗属性',
        'target_physical_resistance': '物理抗性',
        'target_magic_resistance': '魔法抗性',
        'proration': '惯性加成',
        'stability': '稳定率',
        'probability_of_graze': 'Graze机率',
        'skill_level_long_range': '((!远程狙击))等级',
        'combo_multiplier': '连击倍率',
        'other_multiplier': '其它倍率',
      },
    },
  };
}
