root: true
env:
  node: true
extends:
  - plugin:vue/vue3-essential
  - eslint:recommended
parserOptions:
  parser: babel-eslint
plugins:
  - jsdoc
  - import
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
    webpack:
      config: node_modules/@vue/cli-service/webpack.config.js
  import/extensions:
    - .js
    - .ts
  jsdoc:
    mode: closure
globals:
  defineProps: readonly
  defineEmits: readonly
  defineExpose: readonly
  withDefaults: readonly
rules:
  jsdoc/no-undefined-types: warn
  no-unused-vars: warn
  no-trailing-spaces: warn
  object-curly-spacing:
    - warn
    - always
  eol-last:
    - error
    - always
  comma-spacing:
    - warn
    - before: false
      after: true
  comma-dangle:
    - warn
    - always-multiline
  no-shadow:
    - error
  no-use-before-define:
    - error
    - functions: false
      classes: false
  no-void:
    - error
  quotes:
    - error
    - single
  import/no-unresolved:
    - 2
    - commonjs: true
  vue/html-indent:
    - warn
    - 2
  vue/max-attributes-per-line:
    - warn
    - singleline:
        max: 5
        allowFirstLine: true
      multiline:
        max: 1
        allowFirstLine: false
  vue/html-closing-bracket-newline:
    - warn
    - singleline: never
      multiline: always
  vue/comma-dangle:
    - warn
    - always-multiline
  vue/custom-event-name-casing:
    - error
    - kebab-case
  vue/prop-name-casing:
    - error
    - camelCase
  vue/attribute-hyphenation:
    - error
    - always
  vue/v-on-event-hyphenation:
    - error
    - always
  vue/component-tags-order:
    - error
    - order:
        - - template
          - script
        - style
  vue/component-name-in-template-casing:
    - warn
    - PascalCase
  vue/attributes-order:
    - error
  vue/require-explicit-emits:
    - error
  vue/block-tag-newline:
    - error
  vue/no-potential-component-option-typo:
    - error
    - presets:
        - all
      custom:
        - RegisterLang
  vue/v-on-function-call:
    - error
    - never
  vue/valid-define-props:
    - error
  vue/valid-define-emits:
    - error
